###

GET {{url}}

###

GET {{url}}/posts

###

GET {{url}}/posts/1

###

POST {{url}}/posts
Content-Type: application/json

{
	"title": "Titre du post 2",
	"slug": "title-4",
	"content": "Contenu du post"
}

###

PUT {{url}}/posts/3
Content-Type: application/json

{
	"title": "Titre du post modifié",
	"slug": "title-6",
	"content": "Contenu du post"
}

###

DELETE {{url}}/posts/3