###

GET {{url}}

###

GET {{url}}/posts

###

GET {{url}}/posts/fd

###

POST {{url}}/posts
Content-Type: application/json

{
	"userId": 1,
	"title": "Titre du post 2",
	"content": "Contenu du post",
	"createdAt": "2020-11-03 09:22:06"
}

###

PUT {{url}}/posts/3
Content-Type: application/json

{
	"title": "Titre du post modifié",
	"content": "Contenu du post"
}

###

DELETE {{url}}/posts/3