###

GET {{url}}

###

GET {{url}}/users

###

GET {{url}}/users/1

###

POST {{url}}/users
Content-Type: application/json

{
	"email": "j.delatour@gmail.com",
	"password": "password",
	"firstname": "Jean",
	"lastname": "Delatour",
	"username": "thisisjean",
	"biography": "lorem ipsum",
	"isAdmin": false
}

###

PUT {{url}}/users/2
Content-Type: application/json

{
	"email": "j.delatour@gmail.com",
	"password": "password",
	"newPassword": "password2",
	"firstname": "Jean",
	"lastname": "Delatour",
	"username": "thisisjean",
	"biography": "lorem ipsum 2",
	"isAdmin": false
}

###

DELETE {{url}}/users/5