###

###

GET http://localhost:3000

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/dfdfs

###

POST http://localhost:3000/users
Content-Type: application/json

{
	"id": 1,
	"email": "jean.delatour@gmail.com",
	"firtname": "Jean",
	"lastname": "Delatour",
	"biography": "lorem ipsum",
	"isAdmin": false,
	"createdAt": "2020-10-15 17:18:13",
	"updatedAt": "2020-10-15 17:18:13"
}

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
	"id": 1,
	"email": "jean.delatour@gmail.com",
	"firtname": "Jean",
	"lastname": "Delatour",
	"biography": "lorem ipsum",
	"isAdmin": false,
	"createdAt": "2020-10-15 17:18:13",
	"updatedAt": "2020-10-15 17:18:13"
}

###

DELETE http://localhost:3000/users/1



