###

GET http://localhost:3000

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

POST http://localhost:3000/users
Content-Type: application/json

{
	"email": "j.delatour@gmail.com",
	"password": "password",
	"firstname": "Jean",
	"lastname": "Delatour",
	"username": "thisisjean",
	"biography": "lorem ipsum",
	"isAdmin": false
}

###

PUT http://localhost:3000/users/2
Content-Type: application/json

{
	"email": "j.delatour@gmail.com",
	"password": "password",
	"newPassword": "password2",
	"firstname": "Jean",
	"lastname": "Delatour",
	"username": "thisisjean",
	"biography": "lorem ipsum 2",
	"isAdmin": false
}

###

DELETE http://localhost:3000/users/5