###

GET http://localhost:8000

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

POST http://localhost:3000/users
Content-Type: application/json

{
	"email": "j.delatour@gmail.com",
	"firstname": "Jean",
	"lastname": "Delatour",
	"biography": "lorem ipsum",
	"isAdmin": false,
	"createdAt": "2020-11-03 09:22:06"
}

###

PUT http://localhost:3000/users/3
Content-Type: application/json

{
	"email": "j.delatour@gmail.com",
	"firstname": "Jean",
	"lastname": "Delatour",
	"biography": "lorem ipsum 2",
	"isAdmin": false
}

###

DELETE http://localhost:3000/users/5