CREATE TABLE IF NOT EXISTS `users` (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  biography TEXT NOT NULL,
  isAdmin BOOLEAN DEFAULT false,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8